### ISSUE TITLE
Video fails to load

### ISSUE THREAD

**Issue by zang74** [mortael/corridor#7]
### Details
I can view  episode lists just fine, but the second I click on them, I get this error:

2024-07-14 19:11:30.194 T:461645   debug <general>: ------ Window Deinit (DialogNotification.xml) ------
2024-07-14 19:11:30.639 T:602563   debug <CAddonSettings[0@plugin.video.corridor]>: trying to load setting definitions from old format...
2024-07-14 19:11:31.096 T:602563   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'token'
                                                   Traceback (most recent call last):
                                                     File "/home/superuser/.kodi/addons/plugin.video.corridor/main.py", line 210, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/superuser/.kodi/addons/plugin.video.corridor/main.py", line 193, in router
                                                       play_video(params['video'])
                                                     File "/home/superuser/.kodi/addons/plugin.video.corridor/main.py", line 137, in play_video
                                                       token = api.login()
                                                               ^^^^^^^^^^^
                                                     File "/home/superuser/.kodi/addons/plugin.video.corridor/resources/lib/api.py", line 33, in login
                                                       token = r.json()['token']
                                                               ~~~~~~~~^^^^^^^^^
                                                   KeyError: 'token'
                                                   -->End of Python script error report<--

**Comment by mortael** [comment]
Better late then never, it should be working again :)

**Comment by zang74** [comment]
Sorry for the delayed response. Long story short, even with the add-on update to 1.3.6, InputStream on Kodi 21.2 crashed out every time I'd try and load a corridor video (or any DRM protected video for that matter). The only fix to this InputStream problem is Kodi 21.3, which has been notoriously painful to either successfully build or install (outside of a buggy, sandboxed Flatpak) on Ubuntu ≤25.10. Resolute Raccoon's build of Kodi thankfully happens to be 21.3, which fixes said problem. 

So, installing Ubuntu 26.04 finally gave me the chance to use this update and it works perfectly. Thank you.
